### PR TITLE
Fix sleeping in FluentFunctions retry

### LINKED ISSUE #475: FluentFunctions retry does not sleep when exceptions occur
I'm playing around with cyclops to perform some basic retry functionality and it appears the `retry` method doesn't sleep properly when an exception occurs.

Here is my intellij idea snippet:
```java
import cyclops.function.FluentFunctions;

class FluentTest {
    public static void main(String[] args) {
        final Test test = new Test();
        FluentFunctions.checkedExpression(test::getName)
                .retry(3, 5000)
                .apply("bob");
    }

    static class Test {
        private static int failed = 0;

        public void getName(final String name) {
            if (failed < 2) {
                failed++;
                System.out.println("error");
                throw new RuntimeException("error");
            }
            System.out.println("name = " + name);
        }
    }
}

// output
error
error
name = bob
```

This should take around 10 seconds to finish but it finishes immediately. I'm using dependency version: `com.aol.simplereact:cyclops-react:2.0.0-MI2`.

Looking at the code in `retry`, it would seem this line:
```java
ExceptionSoftener.softenRunnable(() -> Thread.sleep(sleep.get()));
```
Would need to change to something like:
```java
final Runnable r = ExceptionSoftener.softenRunnable(() -> Thread.sleep(sleep.get()));
r.run(); // runs synchronously
```

### PR DESCRIPTION
**Pull request by jlorenzen**
Updates FluentFunctions.retry to call the sleep
runnable so the call actually sleeps.

Fixes #475 

I couldn't find a good way to write a test for this scenario as it wouldn't be very deterministic unless I made the retry time longer and diff'd the start and end times.

### CODE REVIEW

File: src/main/java/cyclops/function/FluentFunctions.java [hunk 1]
```diff
@@ -464,7 +464,8 @@ private String handleNameEnd() {
                     } catch (final Throwable e) {
                         exception = e;
                     }
-                    ExceptionSoftener.softenRunnable(() -> Thread.sleep(sleep.get()));
+                    ExceptionSoftener.softenRunnable(() -> Thread.sleep(sleep.get()))
+                            .run();
```
Comment (davidartplus) [inline src/main/java/cyclops/function/FluentFunctions.java]: Looks good

**Comment by johnmcclean-aol** [comment]
Yep - fix looks good. Thanks a million for reporting + fixing this!

**Comment by jlorenzen** [comment]
@johnmcclean-aol What version will this be included in and when do you think that will get released?

**Comment by johnmcclean-aol** [comment]
It will be in 2.0.0-MI3 - optimistically it might make it out later in this week, more realistically sometime next week is likely.
